export interface CaseStudyMeta {
  slug: string
  title: string
  subtitle: string
  category: 'personal-brands' | 'business-websites' | 'ai-programs'
  image: string
  highlights: string[]
  description: string
  summary: string
  challenge: string[]
  approach: string[]
  result: string[]
  detailImages: string[]
  beforeAfter?: boolean
  website?: string
  websiteLabel?: string
  blogLink?: string
}

export const allCaseStudies: CaseStudyMeta[] = [
  // ─── PERSONAL BRANDS ────────────────────────────────────────────────
  {
    slug: 'rich-pham-personal-brand',
    title: 'Rich Pham',
    subtitle: 'Executive Leadership Reimagined',
    category: 'personal-brands',
    image: '/case studies/images/case studies-personal brands-Rich Pham.jpeg',
    highlights: ['Thought Leadership', 'SEO', 'GEO'],
    description: 'Personal branding strategy powered by AI agents.',
    summary: "Rich Pham's personal brand platform captures his transformation from entry-level roles to C-suite leadership, founding multiple companies, and navigating setbacks and successes across industries and countries. Built after his exit from Pocari Sweat, the site positions him as a trusted advisor to executives and business owners, combining authenticity with strategic insight to inspire action and accelerate growth.",
    challenge: [
      'Needed to transition from corporate executive to independent consultant without losing credibility',
      'Required a brand voice that balanced humility with authority',
      'No central platform to showcase leadership philosophies, case examples, and service offerings',
      'Limited time for ongoing content creation while building a client base',
    ],
    approach: [
      'Designed a clean, confident personal brand website anchored by a powerful origin story and clear service pathways',
      'Structured content into Leadership Insights, Growth Strategies, and Scaling Systems to match audience needs',
      'Integrated an AI-powered content workflow to draft blogs, LinkedIn posts, and email updates in Rich\'s voice',
      'Built SEO-ready pages targeting leadership consulting and executive growth keywords',
      'Crafted a lead-generation funnel that nurtures warm contacts into booked consultations',
    ],
    result: [
      'A polished digital hub that builds instant trust with C-level audiences',
      'Clear positioning as a leadership strategist with a proven, global track record',
      'Ongoing content engine producing thought leadership with minimal manual effort',
      'Early client wins directly attributed to the website\'s credibility and storytelling',
    ],
    detailImages: ['/case studies/personal brands/rich-pham/casestudy_personal-brands-rich-pham.jpg'],
    website: 'https://www.richpham.com/',
    websiteLabel: 'View Website',
    blogLink: 'https://www.edge8.ai/post/master-personal-branding-in-2025-with-ai-agents-and-geo',
  },
  {
    slug: 'angi-hurt-personal-brand',
    title: 'Angi Hurt',
    subtitle: "Building the Midwest's Strategic Nexus",
    category: 'personal-brands',
    image: '/case studies/images/case studies-personal brands-Angi Hurt.jpeg',
    highlights: ['Content Automation', 'LinkedIn Growth'],
    description: 'AI-driven personal brand for executive leader.',
    summary: "Angi Hurt's personal brand website transforms her reputation for connecting business leaders into a central hub for collaboration, mentorship, and growth. By weaving her small-town authenticity with corporate expertise, the platform elevates her visibility and strengthens her role as a catalyst for Midwest business innovation.",
    challenge: [
      'Needed a cohesive online presence to connect her diverse professional activities',
      'Wanted to expand influence beyond local circles without losing regional authenticity',
      'No formal platform to highlight her track record, partnerships, and insights',
      'Required a scalable system for sharing updates, articles, and opportunities',
    ],
    approach: [
      'Developed a personal brand website blending Midwest values with a polished, professional aesthetic',
      'Organized content into Partnership Stories, Leadership Insights, and Growth Opportunities',
      'Created a blog strategy targeting collaboration, networking, and regional growth keywords',
      'Integrated AI-driven publishing for regular LinkedIn and newsletter content',
      'Designed a partnership inquiry form and event calendar to encourage engagement',
    ],
    result: [
      'A credible, accessible platform positioning Angi as a go-to regional connector',
      'Strengthened brand recognition across multiple Midwest markets',
      'Scalable content and events calendar that keeps her network engaged year-round',
      'New partnership inquiries generated within weeks of launch',
    ],
    detailImages: ['/case studies/personal brands/angi-hurt/casestudy_personal-brands-angi-hurt.jpg'],
    website: 'https://www.angihurt.com/',
    websiteLabel: 'View Website',
    blogLink: 'https://www.edge8.ai/post/master-personal-branding-in-2025-with-ai-agents-and-geo',
  },
  {
    slug: 'david-jackson-personal-brand',
    title: 'David Jackson',
    subtitle: "Illuminating Vietnam's Real Estate Landscape",
    category: 'personal-brands',
    image: '/case studies/images/case studies-personal brands-David Jackson.jpeg',
    highlights: ['SEO', 'Authority Building'],
    description: 'Systematic personal brand built with AI agents.',
    summary: "David Jackson's personal brand site establishes him as a trusted source for Vietnam's evolving property market. Backed by nearly two decades of experience and his role leading Avison Young Vietnam & Cambodia, the platform combines deep market insights with a people-first leadership approach, appealing to both investors and development partners.",
    challenge: [
      'Needed to distill complex real estate market analysis into accessible content',
      'Required a balance between professional authority and personal authenticity',
      'Lacked a single platform integrating thought leadership, media, and speaking engagements',
      'Wanted to stand out among international real estate voices in the region',
    ],
    approach: [
      'Built a modern, authoritative website with dedicated sections for Market Insights, Leadership Philosophy, and Speaking Engagements',
      'Implemented GEO-optimized blog publishing for visibility on AI-driven search platforms',
      'Developed a content calendar focused on market trends, investment strategies, and sustainability in Southeast Asia',
      'Integrated media features, podcasts, and downloadable reports to increase engagement',
      'Ensured mobile-first design for busy, on-the-go professional audiences',
    ],
    result: [
      'A definitive online resource for Vietnam real estate expertise',
      'Increased inbound speaking requests and media invitations',
      'Higher visibility for investment-focused content in search and AI platforms',
      'Strengthened reputation as a cross-cultural leader in the property sector',
    ],
    detailImages: ['/case studies/personal brands/david-jackson/casestudy_personal-brands-david-jackson.jpg'],
    website: 'https://www.davidmjacko.com/',
    websiteLabel: 'View Website',
    blogLink: 'https://www.edge8.ai/post/master-personal-branding-in-2025-with-ai-agents-and-geo',
  },
  {
    slug: 'steve-muller-personal-brand',
    title: 'Steve Muller',
    subtitle: 'Storytelling Vietnam Through Vespa Adventures',
    category: 'personal-brands',
    image: '/case studies/images/case studies-personal brands-Steve Muller.jpeg',
    highlights: ['Thought Leadership', 'Content Strategy'],
    description: 'AI-powered leadership brand at scale.',
    summary: "Steve Muller's personal brand site, built around Vespa Adventures, brings Vietnam's culture and landscapes to life through immersive storytelling. Designed to resonate with travelers seeking authentic, sustainable experiences, the platform showcases his passion while driving tour bookings and brand partnerships.",
    challenge: [
      'Needed to showcase personal passion while reinforcing business credibility',
      'Required an experience-driven design to capture the excitement of Vespa travel',
      'Wanted to integrate sustainability messaging without sounding commercial',
      'No system for scaling story-driven content across web, blog, and social',
    ],
    approach: [
      'Created a visually immersive website balancing Travel Stories, Sustainable Tourism Initiatives, and Booking Integration',
      'Used narrative-driven SEO targeting experiential travel keywords',
      'Developed an AI-assisted content engine for continuous storytelling output',
      'Incorporated guest stories, user-generated content, and photography galleries to build authenticity',
      'Built a blog hub optimized for both organic search and GEO-based AI discovery',
    ],
    result: [
      'A distinctive personal brand presence that merges passion with professionalism',
      'Increased brand recall among travelers seeking culturally rich experiences',
      'Growth in organic bookings linked directly to storytelling content',
      'A sustainable platform ready for future expansion into media and partnerships',
    ],
    detailImages: ['/case studies/personal brands/steve-muller/casestudy_personal-brands-steve-muller.jpg'],
    website: 'https://www.stevesvespa.com/',
    websiteLabel: 'View Website',
    blogLink: 'https://www.edge8.ai/post/master-personal-branding-in-2025-with-ai-agents-and-geo',
  },

  // ─── BUSINESS WEBSITES ──────────────────────────────────────────────
  {
    slug: 'vespa-adventures',
    title: 'Vespa Adventures',
    subtitle: 'Rebuild Their Digital Experience to Drive Growth',
    category: 'business-websites',
    image: '/case studies/images/case studies-business website-Vespa Adventures.jpeg',
    highlights: ['Conversion Optimization', 'SEO', 'AI Content'],
    description: 'Adventure travel website transformed by AI marketing.',
    summary: "Vespa Adventures is Southeast Asia's leading Vespa tour operator, known for immersive local experiences across Vietnam, Cambodia, and Thailand. The company needed a website that not only showcased their personality and cultural experiences, but also captured, nurtured, and converted interest from global travelers into real bookings.",
    challenge: [
      'An outdated ecommerce site that didn\'t reflect "The Ride of Your Life" brand promise',
      'Manual, disconnected booking processes',
      'No structure to support discovery-phase travelers',
      'No SEO or authority content strategy to capture high-intent traffic',
    ],
    approach: [
      'Built a fully integrated booking + CRM system',
      'Developed authority pages aligned with top search intents (e.g., "Things to Do in Hanoi")',
      'Created blog-driven funnels to guide discovery → interest → booking',
      'Launched lead magnets and nurture flows for better conversion rates',
    ],
    result: [
      'A system that captures travelers earlier in their planning process',
      'Automated lead flows and CRM integration for better visibility and tracking',
      'A site built for discovery, booking, and long-term brand engagement',
      '10,000 to 18,000 indexed words, signaling strong SEO content growth',
      '135% increase in organic traffic year-over-year',
      'Hanoi tour sales increased by 35%, with more travelers converting from blog traffic to booked tours',
    ],
    detailImages: [
      '/case studies/business-websites/vespa-adventures/vespa-adventures-before.jpeg',
      '/case studies/business-websites/vespa-adventures/vespa-adventures-after.jpeg',
    ],
    beforeAfter: true,
    website: 'https://vespaadventures.com/',
    websiteLabel: 'View Website',
  },
  {
    slug: 'pho24',
    title: 'PHO24',
    subtitle: 'Redesigning PHO24® for Global Reach & Franchise Growth',
    category: 'business-websites',
    image: '/case studies/images/case studies-business website-PHO24.jpeg',
    highlights: ['Brand Refresh', 'Digital Presence', 'AI Content'],
    description: 'Restaurant chain digital transformation with AI.',
    summary: 'PHO24® is Vietnam\'s most iconic pho restaurant brand, with over 20 years of heritage and global recognition. As the company pursued international expansion, it needed a digital foundation to support franchise growth and brand storytelling—balancing speed, search optimization, and cultural authenticity.',
    challenge: [
      'Outdated website design not aligned with their global positioning',
      'Poor SEO performance with limited content structure',
      'No franchise funnel or strategy to capture new leads',
      'Sluggish page speed and mobile UX gaps',
    ],
    approach: [
      'Designed a clean, modern interface aligned with PHO24®\'s evolving brand identity',
      'Rebuilt the SEO structure from the ground up, including content library, internal linking, and metadata',
      'Created new content blocks focused on cultural insights, recipes, and franchise pathways',
      'Optimized performance and responsiveness across all devices',
    ],
    result: [
      'A fast, scalable, and SEO-optimized website that feels both authentic and global',
      'Clear CTAs and content flows that engage pho lovers and franchise partners alike',
      'Strong foundations for future international growth and digital content expansion',
    ],
    detailImages: [
      '/case studies/business-websites/pho24/pho24-before.jpg',
      '/case studies/business-websites/pho24/pho24-after.jpg',
    ],
    beforeAfter: true,
  },
  {
    slug: 'investmigrate',
    title: 'InvestMigrate',
    subtitle: 'Building a Trusted EB-3 Page That Converts',
    category: 'business-websites',
    image: '/case studies/images/case studies-business website-InvestMigrate.jpeg',
    highlights: ['Lead Generation', 'SEO', 'GEO'],
    description: 'Investment migration platform powered by AI.',
    summary: 'InvestMigrate is a U.S.-based immigration consultancy helping skilled professionals navigate visa options like EB-3. To build trust with Nigerian audiences, they needed a high-performance content funnel tailored to the needs, search behavior, and skepticism of the local market.',
    challenge: [
      'No dedicated entry point for Nigerian EB-3 visa applicants',
      'Scattered messaging and low SEO performance for relevant search terms',
      'Lack of trust signals for an audience wary of scams',
      'No content funnel guiding users from search to consultation',
    ],
    approach: [
      'Designed and built a dedicated EB-3 visa authority page targeting Nigerian professionals',
      'Integrated success stories, visual trust cues, and localized messaging',
      'Optimized for search queries like "EB-3 visa Nigeria" and "U.S. work visa for unskilled workers"',
      'Built a supporting internal linking structure from blog content to strengthen SEO',
    ],
    result: [
      'A high-converting landing page that acts as the digital center of the EB-3 funnel',
      'Clearer, more confident positioning for Nigerian professionals and families',
      'Stronger lead quality and improved consultation-to-application conversion rate',
    ],
    detailImages: [
      '/case studies/business-websites/investmigrate/InvestMigrate-before.jpg',
      '/case studies/business-websites/investmigrate/InvestMigrate-after.jpg',
    ],
    beforeAfter: true,
  },
  {
    slug: 'grady-golf',
    title: 'Grady Golf',
    subtitle: 'Building a Beginner-First Golf Brand',
    category: 'business-websites',
    image: '/case studies/images/case studies-business website-Grady Golf.jpeg',
    highlights: ['E-commerce', 'AI Personalization', 'Conversion'],
    description: 'Golf equipment brand with AI-driven marketing.',
    summary: 'Grady Golf is a new golf brand that aims to make the sport more accessible and less intimidating for first-time players. They needed a website that could educate, inspire, and convert—all in one place—without overwhelming beginners with technical jargon or high-pressure sales.',
    challenge: [
      'Golf perceived as intimidating, exclusive, and complicated for beginners',
      'No structure for combining education and ecommerce',
      'Needed a tone-consistent, beginner-friendly brand identity',
      'Limited team capacity to scale content across blog, social, and product',
    ],
    approach: [
      'Built a dual-path Wix website that balances "Learn" and "Shop" journeys',
      'Created the Grady Learning Lab: 17-part educational flow with a 90-day roadmap',
      'Developed a branded AI prompt engine to generate content at scale',
      'Implemented referral-ready ecommerce checkout and product system',
      'Conducted SEO audits and built blog content pillars aligned with long-tail search behavior',
    ],
    result: [
      'A scroll-friendly, clean, and warm digital brand tailored to new golfers',
      'A structured journey that helps first-timers learn, shop, and build confidence',
      'SEO-ready content system and blog hub built for discoverability and growth',
      'Brand identity and voice system ready for future campaigns and partnerships',
    ],
    detailImages: ['/case studies/business-websites/grady-golf/grady-golf.jpg'],
  },
  {
    slug: 'nhau-vodka',
    title: 'Nhau Vodka',
    subtitle: "Launching Vietnam's First Story-Driven Vodka Brand",
    category: 'business-websites',
    image: '/case studies/images/case studies-business website-Nhau Vodka.jpeg',
    highlights: ['Brand Launch', 'Digital Strategy', 'AI Content'],
    description: 'Premium spirits brand launched with AI marketing.',
    summary: 'Alchemy Asia partnered with Edge8 to launch Nhậu Vodka—Vietnam\'s first rice vodka inspired by nhậu culture. The project needed to translate cultural pride into a modern brand narrative while complying with strict regulations on alcohol marketing.',
    challenge: [
      'No direct sales allowed due to alcohol regulations',
      'Needed to educate a younger generation on "nhậu" culture without sounding old-fashioned',
      'Required strong SEO visibility in a highly restricted advertising category',
      'Platform had to run on Squarespace per client request, limiting backend customization',
    ],
    approach: [
      'Built a sleek, regulation-compliant Squarespace website with custom-coded popup age gate',
      'Developed a storytelling-first architecture with editorial-style navigation: Vodka, Cocktails, Nhậu Tales, Where To Nhậu, Buy Nhậu',
      'Created content pillars rooted in Vietnamese lifestyle and rituals: "How to Nhậu", "Tâm Sự", and "Craftsmanship"',
      'Used prompt engineering to build an AI-powered content system for future blog and social posts',
      'Implemented a social UGC campaign around #MyNhậuMoment to promote organic brand engagement',
    ],
    result: [
      'A visually rich brand experience blending culture, community, and compliance',
      'Organic SEO visibility built on brand storytelling instead of paid ads',
      'Culturally nuanced site that resonates with Gen Z and millennial audiences',
      'Strategic launchpad for future product extensions and campaigns',
    ],
    detailImages: ['/case studies/business-websites/nhau-vodka/nhau-vodka.jpg'],
  },
  {
    slug: 'ai-officer-institute',
    title: 'AI Officer Institute',
    subtitle: 'Launching an AI Certification Ecosystem',
    category: 'business-websites',
    image: '/case studies/images/case studies-business website-AI Officer Institute.jpeg',
    highlights: ['Education Platform', 'SEO', 'Lead Generation'],
    description: 'AI education platform built for scale.',
    summary: 'The AI Officer Institute was created to meet the rising demand for professionals who can lead AI inside organizations. Edge8 developed the full go-to-market stack: from naming, branding, and website development to SEO content, certification logic, and launch strategy.',
    challenge: [
      'New, undefined role in the market: "AI Officer"',
      'Needed a trusted and professional brand presence',
      'Required educational credibility while feeling startup-agile',
      'Circle community and certification stack needed to integrate seamlessly',
    ],
    approach: [
      'Created a full brand identity and purpose framework based on founder interviews',
      'Built a responsive website with SEO-rich content, landing pages, and blog',
      'Developed a multi-level certification system aligned with business use cases',
      'Designed Circle community onboarding and content experience',
      'Planned an 8-day launch calendar with social, email, and event strategies',
    ],
    result: [
      'Launch-ready platform with clear positioning for business leaders and professionals',
      'Scalable community + certification engine',
      'Trusted voice in the AI education ecosystem',
      'Official launch executed with a structured growth roadmap',
    ],
    detailImages: ['/case studies/business-websites/ai-officer-institute/ai-officier-institute.jpg'],
  },
  {
    slug: 'fab-four-academy',
    title: 'Fab Four Academy',
    subtitle: 'From Passion to Business: The Fab Four Academy Launch',
    category: 'business-websites',
    image: '/case studies/images/case studies-business website-Fab Four Academy.jpeg',
    highlights: ['Music Education', 'AI Marketing', 'Enrollment'],
    description: 'Music academy grown with AI-powered digital strategy.',
    summary: "Fab Four Academy transforms The Beatles' legendary journey into actionable leadership lessons for Gen X executives. Edge8 developed the complete digital foundation: a brand book, full website with conversion-optimized pages, automated daily wisdom email system, and comprehensive SEO strategy.",
    challenge: [
      'Balancing authenticity with clear business goals',
      'Differentiation in a crowded leadership education market',
      'Balancing nostalgia with professionalism',
      'No existing digital presence',
      'Needed to position Dan Absher as a credible thought leader',
    ],
    approach: [
      'Laid the groundwork with deep audience and competitive research',
      'Deployed a multi-touchpoint conversion strategy across web, email, and social',
      'Built a content-first brand identity rooted in Beatles storytelling and leadership parallels',
      'Executed a funnel-based launch strategy to drive early subscribers and engagement',
    ],
    result: [
      '11,000+ site events in the first two months, demonstrating strong early engagement',
      'Nearly 100 subscribers in the first 60 days, confirming genuine market interest',
      'A distinctive, memorable brand that bridges pop culture and executive development',
      'Automated email system delivering daily leadership wisdom at scale',
    ],
    detailImages: ['/case studies/business-websites/fab-four-academy/fab-four-academy.jpg'],
  },

  // ─── AI PROGRAMS ────────────────────────────────────────────────────
  {
    slug: 'kyungbang-ai-program',
    title: 'Kyungbang',
    subtitle: 'AI-Powered Quality Platform for Global Textile Manufacturing',
    category: 'ai-programs',
    image: '/case studies/images/case studies-ai programs-Kyungbang.jpeg',
    highlights: ['AI Program', 'Manufacturing', 'Data Systems'],
    description: 'Enterprise AI program for global manufacturing.',
    summary: "Kyungbang, a global textile manufacturer, manages one of the most complex challenges in its industry: high-volume fiber testing across suppliers and factories worldwide. Data arrived in scattered formats—PDFs, Excel sheets, raw text—forcing engineers to spend hours reconciling numbers before making decisions. Edge8 partnered with Kyungbang to build an AI-powered quality platform designed to unify that data, flag anomalies in real time, and allow engineers to query results in natural language.",
    challenge: [
      'Supplier and factory data scattered across inconsistent formats (PDF, Excel, text)',
      'Manual entry of results into spreadsheets, then printed for review',
      'No direct connectivity from testing machines to decision-makers',
      'Engineers lacked intuitive tools to quickly query or compare test outcomes',
    ],
    approach: [
      'Built an AI-driven document parsing engine to ingest QC reports from any format',
      'Developed a system for real-time anomaly detection and automated flagging',
      'Enabled natural language querying for batch, machine, and location histories',
      'Integrated the system directly into existing QC workflows across facilities',
    ],
    result: [
      'Reduced manual reconciliation time by over 50%',
      'Engineers retrieve insights instantly using everyday language instead of spreadsheets',
      'Faster, more confident production decisions across multiple facilities',
      'Established a scalable foundation for predictive blending and future AI-driven enhancements',
    ],
    detailImages: ['/case studies/ai-programs/kyungbang/kyungbang.jpeg'],
  },
  {
    slug: 'veracity-ai-program',
    title: 'Veracity',
    subtitle: 'Co-CEO AI Agent for EOS-Aligned Leadership',
    category: 'ai-programs',
    image: '/case studies/images/case studies-ai programs-Veracity.jpeg',
    highlights: ['AI Agents', 'Market Intelligence', 'Automation'],
    description: 'AI intelligence program for market research firm.',
    summary: "Veracity Consulting, an IT services firm operating on the Entrepreneurial Operating System (EOS), set out to build an intelligent Co-CEO assistant for its founder, Angela Hurt. The vision: an AI partner that could answer internal questions, route requests to the right leader, and surface structured decision support in real time. The goal is not just efficiency, but to provide data-driven clarity that balances the founder's natural people-first, intuition-driven style with structured, evidence-based insight.",
    challenge: [
      'Often when key decisions arise, the right data isn\'t available or connected',
      'Input from the team tends toward consensus, not clear recommendations',
      'Leading indicators aren\'t consistently tied to long-term revenue outcomes',
      'Important context (values, culture, performance patterns) lives in people\'s heads, not systems',
    ],
    approach: [
      'Designed a data pipeline to unify leadership profiles, EOS tools, and business metrics',
      'Trained AI agents to "think" like Veracity\'s key influencers and domain leaders',
      'Embedded cultural values and decision-making principles into the system logic',
      'Structured outputs to surface insights, route requests, and recommend next steps with clarity',
    ],
    result: [
      'Weekly leadership meetings are recorded and saved into the database, giving Angela on-demand access to review notes',
      'Prototype agents provide structured summaries that highlight key themes and action items',
      'EOS tools, leadership profiles, and financial goals are being connected into a unified data foundation',
      'Early outputs show clearer visibility into leading indicators and how they tie to long-term revenue targets',
    ],
    detailImages: ['/case studies/ai-programs/veracity/veracity.jpeg'],
    website: 'https://veracityit.com/',
    websiteLabel: 'View Website',
  },
  {
    slug: 'wink-hotels-travel-buddy',
    title: 'Wink Hotels (Travel Buddy)',
    subtitle: 'Redefining Guest Experience Through AI Travel Assistant',
    category: 'ai-programs',
    image: '/case studies/images/case studies-ai programs-Wink Hotels (Travel Buddy).jpeg',
    highlights: ['AI Concierge', 'Hospitality', 'Guest Experience'],
    description: 'Travel Buddy AI concierge for hotel group.',
    summary: 'Wink Hotels wanted to create a modern, connected guest experience beyond traditional hotel apps. Travel Buddy was born—a conversational travel assistant designed to guide, entertain, and support guests throughout their stay in Vietnam.',
    challenge: [
      'International guests struggled with language and cultural navigation',
      'Staff had limited bandwidth for personalized recommendations',
      'No digital experience to extend brand storytelling beyond the hotel walls',
    ],
    approach: [
      'Built a multilingual AI chatbot trained on local experiences and FAQs',
      'Designed a Discover Feed to surface nearby attractions, events, and deals',
      'Integrated an audio tour system that auto-detects location for hands-free city guides',
      'Enabled user-generated stories with photos, captions, and sharing tools',
    ],
    result: [
      'A mobile-first guest experience that turns hospitality into exploration',
      'Reduced pressure on front desk and concierge staff',
      'Guests report feeling more connected to Vietnam\'s culture',
      'Unique digital storytelling layer that builds brand loyalty and buzz',
    ],
    detailImages: [
      '/case studies/ai-programs/wink-hotels-travel-buddy/wink-hotels-1.jpeg',
      '/case studies/ai-programs/wink-hotels-travel-buddy/wink-hotels-2.jpeg',
      '/case studies/ai-programs/wink-hotels-travel-buddy/wink-hotels-3.jpeg',
      '/case studies/ai-programs/wink-hotels-travel-buddy/wink-hotels-4.jpeg',
      '/case studies/ai-programs/wink-hotels-travel-buddy/wink-hotels-5.jpeg',
      '/case studies/ai-programs/wink-hotels-travel-buddy/wink-hotels-6.jpeg',
    ],
    website: 'https://wink-hotels.com/en/',
    websiteLabel: 'View Website',
  },
  {
    slug: 'ontarget-abound-health',
    title: 'OnTarget (Abound Health)',
    subtitle: 'Engineering Excellence Across Platforms',
    category: 'ai-programs',
    image: '/case studies/images/case studies-ai programs-OnTarget (Abound Health).jpeg',
    highlights: ['Healthcare AI', 'Patient Engagement', 'Data'],
    description: 'AI program for health-focused enterprise.',
    summary: "OnTarget is Edge8's Vietnam-based engineering team supporting high-velocity tech companies. In this engagement, the team partnered with Abound Health to re-architect mobile pipelines, modernize infrastructure, and implement AI-assisted development practices.",
    challenge: [
      'Unstructured CI/CD pipeline for mobile releases',
      'Outdated Java infrastructure and desktop frontend',
      'Lack of security layers including MFA and API protection',
      'Low test coverage and fragmented technical documentation',
      'No tooling in place for AI-assisted development',
    ],
    approach: [
      'Owned and executed CI/CD pipelines for mobile and desktop',
      'Upgraded from JDK 8 to JDK 17, validating performance and stability',
      'Patched XSS vulnerabilities, secured forgotten password flow, and implemented MFA',
      'Scaled test coverage from 20% to 50% across integration and unit tests',
      'Redesigned user interface with a modern, intuitive layout',
      'Evaluated and implemented GitHub Copilot for AI code assistance',
      'Strengthened peer code review, onboarding docs, and domain-specific knowledge base',
    ],
    result: [
      'Faster, more secure mobile release cycles',
      'Strengthened platform security and maintainability',
      'Significant UI/UX improvements across OnTarget products',
      '30% increase in developer productivity with AI code assist',
      'Enhanced onboarding and technical documentation infrastructure',
      'A resilient engineering culture aligned with innovation and speed',
    ],
    detailImages: [
      '/case studies/ai-programs/ontarget-abound-health/ontarget-abound-health-1.jpeg',
      '/case studies/ai-programs/ontarget-abound-health/ontarget-abound-health-2.jpeg',
    ],
    website: 'https://www.aboundhealth.com',
    websiteLabel: 'View Website',
  },
  {
    slug: 'eo-apac-hubspot',
    title: 'EO APAC Region (HubSpot)',
    subtitle: 'Scaling Membership Systems Across Asia-Pacific',
    category: 'ai-programs',
    image: '/case studies/images/case studies-ai programs-EO APAC Region (HubSpot).jpeg',
    highlights: ['CRM AI', 'APAC Growth', 'HubSpot Integration'],
    description: 'AI-enhanced CRM program for EO APAC region.',
    summary: "Entrepreneurs' Organization (EO) is a global peer-to-peer network for founders and leaders. In the APAC region, membership operations were fragmented—with each chapter using its own set of disconnected tools. Edge8 partnered with EO APAC to centralize operations, streamline onboarding, and bring AI-powered visibility through HubSpot CRM and n8n automations. Starting with a pilot in EO Vietnam, this initiative laid the groundwork for scalable, data-informed growth across the region.",
    challenge: [
      'No unified CRM across EO APAC chapters',
      'Manual processes relied on Excel, Notion, and Google Sheets',
      'Delayed follow-ups for new member applications and event leads',
      'No visibility into performance or progress across chapters',
      'Onboarding and nurturing sequences were inconsistent and labor-intensive',
    ],
    approach: [
      'Deployed HubSpot Sales Hub for EO Vietnam to manage the full membership funnel',
      'Created standardized CRM pipelines for prospects, members, and alumni',
      'Integrated Wix landing pages and Notion forms with HubSpot using n8n workflows',
      'Automated outreach: welcome emails, interest-based nurturing, and internal alerts',
      'Built dashboards for tracking member journey progress and chapter KPIs',
      'Documented a replicable CRM + automation framework for other chapters',
    ],
    result: [
      'Live CRM adoption in EO Vietnam with 100% pipeline visibility',
      'Member leads now receive timely, consistent communications',
      'Admin workload significantly reduced through automation',
      'Improved transparency and data consistency across chapter leadership',
      'Foundation in place to expand to other APAC chapters with minimal friction',
    ],
    detailImages: ['/case studies/ai-programs/eo-apac-region-hubspot/eo-apac-region-hubspot.jpeg'],
    website: 'https://www.eoapac.com',
    websiteLabel: 'View Website',
  },
]

export function getCaseStudyBySlug(slug: string): CaseStudyMeta | undefined {
  return allCaseStudies.find((cs) => cs.slug === slug)
}

export function getCaseStudiesByCategory(
  category: CaseStudyMeta['category']
): CaseStudyMeta[] {
  return allCaseStudies.filter((cs) => cs.category === category)
}

export function getAllCaseStudySlugs(): string[] {
  return allCaseStudies.map((cs) => cs.slug)
}
