// This file contains ONLY the static data - safe to use in client components
export interface PostMeta {
  slug: string
  title: string
  date: string
  category: string
  categorySlug: string
  image: string
  readTime: string
  tags: string[]
  mdFile: string
}

// All 22 blog posts - static data only, no fs imports
export const allPosts: PostMeta[] = [
  // AI in Business
  {
    slug: '2026-ai-trends-5-game-changing-shifts-that-will-define-business-success',
    title: '2026 AI Trends: 5 Game-Changing Shifts That Will Define Business Success',
    date: '2025-11-10',
    category: 'AI in Business',
    categorySlug: 'ai-business',
    image: '/blog/images/2026 AI Trends.jpeg',
    readTime: '8 min read',
    tags: ['AI Trends', 'Business Strategy'],
    mdFile: '2026-ai-trends-5-game-changing-shifts',
  },
  {
    slug: '5-keys-to-reduce-ai-hallucinations-and-build-reliable-business-systems',
    title: '5 Keys to Reduce AI Hallucinations and Build Reliable Business Systems',
    date: '2025-10-15',
    category: 'AI in Business',
    categorySlug: 'ai-business',
    image: '/blog/images/5-Keys.jpg',
    readTime: '6 min read',
    tags: ['AI Reliability', 'Business Systems'],
    mdFile: '5-keys-to-reduce-ai-hallucinations',
  },
  {
    slug: 'ai-data-strategy-why-data-moats-beat-model-wars-in-2025',
    title: 'AI Data Strategy: Why Data Moats Beat Model Wars in 2025',
    date: '2025-09-20',
    category: 'AI in Business',
    categorySlug: 'ai-business',
    image: '/blog/images/AI Data Strategy.jpeg',
    readTime: '7 min read',
    tags: ['Data Strategy', 'AI'],
    mdFile: 'ai-data-strategy-moats-beat-model-wars',
  },
  {
    slug: 'ai-in-data-migration-why-your-ai-program-is-really-a-data-problem',
    title: 'AI in Data Migration: Why Your AI Program Is Really a Data Problem',
    date: '2025-08-12',
    category: 'AI in Business',
    categorySlug: 'ai-business',
    image: '/blog/images/AI in Data Migration-1.jpeg',
    readTime: '6 min read',
    tags: ['Data Migration', 'AI Programs'],
    mdFile: 'ai-in-data-migration',
  },
  {
    slug: 'the-hospitality-data-gap-creating-truly-hotel-personalized-experiences',
    title: 'The Hospitality Data Gap: Creating Truly Hotel Personalized Experiences',
    date: '2025-07-05',
    category: 'AI in Business',
    categorySlug: 'ai-business',
    image: '/blog/images/The Hospitality Data Gap-1.jpeg',
    readTime: '5 min read',
    tags: ['Hospitality', 'Personalization'],
    mdFile: 'hospitality-data-gap-hotel-personalized-experiences',
  },
  {
    slug: 'why-ai-issues-are-really-data-problems-a-guide-for-future-ai-officers',
    title: 'Why AI Issues Are Really Data Problems: A Guide for Future AI Officers',
    date: '2025-06-18',
    category: 'AI in Business',
    categorySlug: 'ai-business',
    image: '/blog/images/Why AI Issues.jpeg',
    readTime: '6 min read',
    tags: ['AI Officers', 'Data'],
    mdFile: 'why-ai-issues-are-really-data-problems',
  },
  {
    slug: 'your-next-ai-hire-isnt-a-person',
    title: "Your Next AI Hire Isn't a Person",
    date: '2025-05-28',
    category: 'AI in Business',
    categorySlug: 'ai-business',
    image: '/blog/images/your next hire.jpeg',
    readTime: '5 min read',
    tags: ['AI Hiring', 'Business'],
    mdFile: 'your-next-ai-hire-isnt-a-person',
  },

  // Founders' Secrets
  {
    slug: 'from-idea-to-interactive-blog-in-30-minutes-the-founders-automation-playbook',
    title: "From Idea to Interactive Blog in 30 Minutes: The Founder's Automation Playbook",
    date: '2025-11-01',
    category: "Founders' Secrets",
    categorySlug: 'founders',
    image: '/blog/images/From Idea to Interactive Blog in 30 Minutes.jpeg',
    readTime: '5 min read',
    tags: ['Automation', 'Content'],
    mdFile: 'from-idea-to-interactive-blog-in-30-minutes',
  },
  {
    slug: 'business-research-assignment-that-could-transform-your-company-and-your-career',
    title: 'The Business Research Assignment That Could Transform Your Company (And Your Career)',
    date: '2025-09-30',
    category: "Founders' Secrets",
    categorySlug: 'founders',
    image: '/blog/images/The Business Research Assignment.jpeg',
    readTime: '6 min read',
    tags: ['Business Research', 'Leadership'],
    mdFile: 'business-research-assignment-transform-your-company',
  },
  {
    slug: 'the-case-for-ai-co-ceos-and-ai-leadership-why-every-leader-needs-a-digital-decision-partner',
    title: 'The Case for AI Co-CEOs & AI Leadership: Why Every Leader Needs a Digital Decision Partner',
    date: '2025-08-20',
    category: "Founders' Secrets",
    categorySlug: 'founders',
    image: '/blog/images/The Case for AI Co-CEOs & AI Leadership.jpeg',
    readTime: '7 min read',
    tags: ['AI Leadership', 'Co-CEO'],
    mdFile: 'case-for-ai-co-ceo-ai-leadership',
  },
  {
    slug: 'why-ai-training-is-essential-for-your-career-success-in-the-digital-age',
    title: 'Why AI Training Is Essential for Your Career Success in the Digital Age',
    date: '2025-07-15',
    category: "Founders' Secrets",
    categorySlug: 'founders',
    image: '/blog/images/Why AI Training Is Essential.jpeg',
    readTime: '5 min read',
    tags: ['AI Training', 'Career'],
    mdFile: 'why-ai-training-is-essential-for-career-success',
  },
  {
    slug: 'why-human-ai-collaboration-is-the-future-of-business-success',
    title: 'Why Human-AI Collaboration Is the Future of Business Success',
    date: '2025-06-10',
    category: "Founders' Secrets",
    categorySlug: 'founders',
    image: '/blog/images/Why Human-AI Collaboration.jpeg',
    readTime: '6 min read',
    tags: ['Human-AI', 'Collaboration'],
    mdFile: 'why-human-ai-collaboration-is-the-future-of-business-success',
  },
  {
    slug: 'why-smart-founders-are-already-planning-for-meta-ray-ban-glasses-even-when-demos-fail',
    title: 'Why Smart Founders Are Already Planning for Meta Ray-Ban Glasses (Even When Demos Fail)',
    date: '2025-05-20',
    category: "Founders' Secrets",
    categorySlug: 'founders',
    image: '/blog/images/Why Smart Founders.jpeg',
    readTime: '5 min read',
    tags: ['AR Glasses', 'Meta'],
    mdFile: 'why-smart-founders-are-planning-for-meta-ray-ban-glasses',
  },

  // Doing Business in Vietnam
  {
    slug: 'how-ai-in-business-success-starts-with-strategic-symbolism',
    title: 'How AI in Business Success Starts with Strategic Symbolism',
    date: '2025-10-25',
    category: 'Doing Business in Vietnam',
    categorySlug: 'vietnam',
    image: '/blog/images/How AI in Business Success Starts with Strategic Symbolism.jpeg',
    readTime: '5 min read',
    tags: ['Vietnam', 'Business Strategy'],
    mdFile: 'how-ai-in-business-success-starts-with-strategic-symbolism',
  },
  {
    slug: 'strategies-to-harness-top-performers-for-business-success',
    title: 'Strategies to Harness Top Performers for Business Success',
    date: '2025-09-12',
    category: 'Doing Business in Vietnam',
    categorySlug: 'vietnam',
    image: '/blog/images/Strategies to Harness Top Performers for Business Success.jpeg',
    readTime: '6 min read',
    tags: ['Performance', 'Vietnam'],
    mdFile: 'strategies-to-harness-top-performers-for-business-success',
  },
  {
    slug: 'tech-in-entrepreneurship-how-ai-is-disrupting-the-role-of-the-founder',
    title: 'Tech In Entrepreneurship: How AI is disrupting the role of the Founder',
    date: '2025-08-05',
    category: 'Doing Business in Vietnam',
    categorySlug: 'vietnam',
    image: '/blog/images/Tech In Entrepreneurship.jpeg',
    readTime: '6 min read',
    tags: ['Entrepreneurship', 'Vietnam'],
    mdFile: 'tech-in-entrepreneurship-how-ai-is-disrupting-the-role-of-the-founder',
  },
  {
    slug: 'vietnam-ai-silicon-valley-of-southeast-asia',
    title: 'Vietnam and the Rise of AI — The New Silicon Valley of Southeast Asia',
    date: '2025-07-22',
    category: 'Doing Business in Vietnam',
    categorySlug: 'vietnam',
    image: '/blog/images/Vietnam and the Rise of AI.jpeg',
    readTime: '7 min read',
    tags: ['Vietnam', 'AI Rise'],
    mdFile: 'vietnam-ai-silicon-valley',
  },
  {
    slug: 'vietnam-ai-business-law-what-leaders-should-know',
    title: "Vietnam's AI Rules — What Leaders Should Know",
    date: '2025-06-28',
    category: 'Doing Business in Vietnam',
    categorySlug: 'vietnam',
    image: "/blog/images/Vietnam's AI Rules.jpeg",
    readTime: '5 min read',
    tags: ['Vietnam', 'AI Regulation'],
    mdFile: 'vietnam-ai-business-law',
  },

  // High Performing Cultures
  {
    slug: 'ai-strategies-for-a-high-performing-culture',
    title: '5 AI Strategies for a High-Performing Culture',
    date: '2025-11-05',
    category: 'High Performing Cultures',
    categorySlug: 'cultures',
    image: '/blog/images/5 AI Strategies.jpeg',
    readTime: '6 min read',
    tags: ['Culture', 'AI Strategy'],
    mdFile: 'ai-strategies-high-performing-culture',
  },
  {
    slug: 'ai-process-culture-performance-automation-that-works',
    title: 'AI for Performance Culture: Process Automation that Works',
    date: '2025-09-25',
    category: 'High Performing Cultures',
    categorySlug: 'cultures',
    image: '/blog/images/AI for Performance Culture-1.jpeg',
    readTime: '6 min read',
    tags: ['Culture', 'Process Automation'],
    mdFile: 'ai-process-culture-performance',
  },
  {
    slug: 'how-one-decision-at-a-time-creates-high-performers-in-business-and-life',
    title: 'How One Decision at a Time Creates High Performers in Business and Life',
    date: '2025-08-18',
    category: 'High Performing Cultures',
    categorySlug: 'cultures',
    image: '/blog/images/How One Decision.jpeg',
    readTime: '5 min read',
    tags: ['Decision Making', 'High Performance'],
    mdFile: 'how-one-decision-at-a-time-creates-high-performers',
  },
  {
    slug: 'offshore-teams-remote-integration-with-ai',
    title: 'Offshore Teams Made Easy | Remote Integration with AI',
    date: '2025-07-10',
    category: 'High Performing Cultures',
    categorySlug: 'cultures',
    image: '/blog/images/Offshore Teams Made Easy.jpeg',
    readTime: '5 min read',
    tags: ['Offshore Teams', 'Remote Work'],
    mdFile: 'remote-team-offshore-integration',
  },
  {
    slug: 'strategies-to-harness-top-performers-hpc',
    title: 'Strategies to Harness Top Performers for Business Success',
    date: '2025-06-05',
    category: 'High Performing Cultures',
    categorySlug: 'cultures',
    image: '/blog/images/Strategies to Harness Top Performers.jpeg',
    readTime: '6 min read',
    tags: ['Performance', 'Culture'],
    mdFile: 'strategies-to-harness-top-performers-for-business-success',
  },
]

export const categories = [
  { slug: 'ai-business', label: 'AI in Business', id: 'ai-business' },
  { slug: 'founders', label: "Founders' Secrets", id: 'founders' },
  { slug: 'vietnam', label: 'Doing Business in Vietnam', id: 'vietnam' },
  { slug: 'cultures', label: 'High Performing Cultures', id: 'cultures' },
]
